"""
Chevalier Events ? Setup Wizard
Run once to configure the app and create a desktop shortcut.
"""
import tkinter as tk
from tkinter import ttk, messagebox
import os, sys, secrets, subprocess, webbrowser, shutil

APP_NAME  = "Chevalier Events"
BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
INST_DIR  = os.path.join(BASE_DIR, "instance")
CFG_PATH  = os.path.join(INST_DIR, "config.py")
LOGO_PATH = os.path.join(BASE_DIR, "frontend", "static", "img", "Chevalier_Logo.jpg")

BURGUNDY  = "#6B1A2A"
GOLD      = "#B8912A"
PARCHMENT = "#F9F5ED"
WHITE     = "#FFFFFF"
INK       = "#1E1208"

# ?? Helpers ???????????????????????????????????????????????????????????????????

def resource(rel):
    return os.path.join(BASE_DIR, rel)


def write_config(data):
    os.makedirs(INST_DIR, exist_ok=True)
    secret = secrets.token_hex(32)
    lines = [
        "# Chevalier Events - instance configuration",
        "# Generated by Setup Wizard. Edit here to change settings.",
        "",
        "SECRET_KEY = " + repr(secret),
        "",
        "ANTHROPIC_API_KEY = " + repr(data["anthropic_key"]),
        "",
        'MAIL_SERVER         = "smtp.gmail.com"',
        "MAIL_PORT           = 587",
        "MAIL_USE_TLS        = True",
        "MAIL_USERNAME       = " + repr(data["gmail"]),
        "MAIL_PASSWORD       = " + repr(data["app_password"]),
        "MAIL_DEFAULT_SENDER = " + repr(data["gmail"]),
        "ADMIN_EMAIL         = " + repr(data["gmail"]),
        "",
        "CHAPTER_NAME        = " + repr(data["chapter_name"]),
        "GRAND_SENECHAL_NAME = " + repr(data["gs_name"]),
    ]
    with open(CFG_PATH, "w", encoding="ascii", errors="replace") as f:
        f.write("\n".join(lines) + "\n")

def create_launcher():
    """Create launcher.bat in the project root."""
    bat = os.path.join(BASE_DIR, "launcher.bat")
    # run.py opens the browser automatically after 1.5s
    content = f'''@echo off
cd /d "{BASE_DIR}"
python run.py
'''
    with open(bat, "w") as f:
        f.write(content)
    return bat


def create_shortcut(bat_path):
    """Create a desktop shortcut using a .vbs script (most reliable on Windows)."""
    # Try standard Desktop first, then OneDrive Desktop
    candidates = [
        os.path.join(os.path.expanduser("~"), "Desktop"),
        os.path.join(os.path.expanduser("~"), "OneDrive", "Desktop"),
        os.path.join(os.path.expanduser("~"), "OneDrive - Personal", "Desktop"),
    ]
    desktop = next((d for d in candidates if os.path.isdir(d)), candidates[0])
    shortcut = os.path.join(desktop, f"{APP_NAME}.lnk")

    # Write a temporary VBScript - more reliable than inline PowerShell
    vbs = os.path.join(BASE_DIR, "_make_shortcut.vbs")
    ico_path = os.path.join(BASE_DIR, "frontend", "static", "img", "chevalier_events.ico").replace("\\", "/")
    vbs_content = f'''Set ws = CreateObject("WScript.Shell")
Set s = ws.CreateShortcut("{shortcut}")
s.TargetPath = "{bat_path}"
s.WorkingDirectory = "{BASE_DIR}"
s.WindowStyle = 1
s.Description = "Launch Chevalier Events"
s.IconLocation = "{ico_path}"
s.Save()
'''
    with open(vbs, "w") as f:
        f.write(vbs_content)

    result = subprocess.run(["cscript", "//Nologo", vbs],
                            capture_output=True, text=True)
    try:
        os.remove(vbs)
    except Exception:
        pass

    if not os.path.exists(shortcut):
        raise RuntimeError(
            f"Could not create Desktop shortcut.\n"
            f"Please create one manually:\n"
            f"Right-click launcher.bat -> Send to -> Desktop (create shortcut)"
        )
    return shortcut



def ensure_admin_can_login():
    """Make sure the admin Person record has can_login=True after setup."""
    try:
        sys.path.insert(0, BASE_DIR)
        from backend import create_app
        app = create_app()
        with app.app_context():
            from backend.models import db, Person
            admins = Person.query.filter_by(is_admin=True).all()
            for p in admins:
                p.can_login = True
            db.session.commit()
    except Exception as e:
        print(f"Note: could not auto-enable admin login: {e}")

# ?? Wizard UI ?????????????????????????????????????????????????????????????????

class SetupWizard(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(f"{APP_NAME} ? Setup")
        self.resizable(True, True)
        self.configure(bg=PARCHMENT)
        self.geometry("560x700")
        self.minsize(520, 620)
        self._center()

        # Shared variables
        self.chapter_name  = tk.StringVar(value="Clos Vougeot")
        self.gs_name       = tk.StringVar(value="")
        self.gmail         = tk.StringVar(value="")
        self.app_password  = tk.StringVar(value="")
        self.anthropic_key = tk.StringVar(value="")
        self.show_pw       = tk.BooleanVar(value=False)

        self._build_header()
        self._build_form()
        self._build_footer()

    def _center(self):
        self.update_idletasks()
        w, h = 560, 700
        x = (self.winfo_screenwidth()  - w) // 2
        y = (self.winfo_screenheight() - h) // 2
        self.geometry(f"{w}x{h}+{x}+{y}")

    def _build_header(self):
        hdr = tk.Frame(self, bg=BURGUNDY)
        hdr.pack(fill="x")
        tk.Label(hdr, text="Chevalier Events",
                 font=("Georgia", 18), fg=GOLD, bg=BURGUNDY,
                 pady=16).pack()
        tk.Label(hdr, text="First-time setup",
                 font=("Arial", 10), fg="#D4B896", bg=BURGUNDY,
                 pady=0, padx=0).pack(pady=(0, 12))

    def _build_form(self):
        # Scrollable frame so content never gets cut off
        canvas = tk.Canvas(self, bg=PARCHMENT, highlightthickness=0)
        scrollbar = ttk.Scrollbar(self, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=scrollbar.set)
        scrollbar.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)
        outer = tk.Frame(canvas, bg=PARCHMENT, padx=30, pady=20)
        outer_id = canvas.create_window((0, 0), window=outer, anchor="nw")

        def _on_resize(event):
            canvas.itemconfig(outer_id, width=event.width)
        canvas.bind("<Configure>", _on_resize)

        def _on_frame_configure(event):
            canvas.configure(scrollregion=canvas.bbox("all"))
        outer.bind("<Configure>", _on_frame_configure)

        # Mouse wheel scrolling
        def _on_mousewheel(event):
            canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
        canvas.bind_all("<MouseWheel>", _on_mousewheel)

        def section(text):
            tk.Label(outer, text=text, font=("Arial", 9, "bold"),
                     fg=BURGUNDY, bg=PARCHMENT).pack(anchor="w", pady=(12,2))
            tk.Frame(outer, bg=GOLD, height=1).pack(fill="x", pady=(0,8))

        def field(parent, label, var, show="", width=38):
            tk.Label(parent, text=label, font=("Arial", 9),
                     fg=INK, bg=PARCHMENT).pack(anchor="w")
            e = tk.Entry(parent, textvariable=var, font=("Arial", 10),
                         show=show, width=width,
                         relief="solid", bd=1)
            e.pack(fill="x", pady=(2, 8))
            return e

        # Chapter
        section("Your Chapter")
        field(outer, "Chapter name", self.chapter_name)
        field(outer, "Your name (Grand S?n?chal)", self.gs_name)

        # Email
        section("Gmail ? for sending emails to members")
        field(outer, "Gmail address", self.gmail)

        pw_frame = tk.Frame(outer, bg=PARCHMENT)
        pw_frame.pack(fill="x")
        tk.Label(pw_frame, text="Gmail App Password", font=("Arial", 9),
                 fg=INK, bg=PARCHMENT).pack(anchor="w")
        self._pw_entry = tk.Entry(pw_frame, textvariable=self.app_password,
                                   font=("Arial", 10), show="*", width=38,
                                   relief="solid", bd=1)
        self._pw_entry.pack(fill="x", pady=(2, 4))
        tk.Checkbutton(pw_frame, text="Show password", variable=self.show_pw,
                       command=self._toggle_pw,
                       font=("Arial", 8), fg=INK, bg=PARCHMENT,
                       activebackground=PARCHMENT).pack(anchor="w")

        # App password help link
        help_frame = tk.Frame(outer, bg="#FFF8EC", relief="solid", bd=1)
        help_frame.pack(fill="x", pady=(4, 0))
        tk.Label(help_frame,
                 text="Need an App Password? You need a Gmail account\n"
                      "with 2-Step Verification enabled.",
                 font=("Arial", 8), fg="#7A5C10", bg="#FFF8EC",
                 justify="left", padx=8, pady=4).pack(side="left")
        tk.Button(help_frame, text="Get one ?",
                  font=("Arial", 8, "underline"), fg=BURGUNDY, bg="#FFF8EC",
                  bd=0, cursor="hand2",
                  command=lambda: webbrowser.open(
                      "https://myaccount.google.com/apppasswords")
                  ).pack(side="right", padx=8)

        # Anthropic
        section("Anthropic API ? for AI seating proposals")
        field(outer, "API key  (sk-ant-?)", self.anthropic_key)
        link = tk.Label(outer, text="Get a free key at console.anthropic.com ?",
                        font=("Arial", 8, "underline"), fg=BURGUNDY, bg=PARCHMENT,
                        cursor="hand2")
        link.pack(anchor="w", pady=(0, 4))
        link.bind("<Button-1>", lambda e: webbrowser.open(
            "https://console.anthropic.com/"))

    def _toggle_pw(self):
        self._pw_entry.config(show="" if self.show_pw.get() else "*")

    def _build_footer(self):
        foot = tk.Frame(self, bg=PARCHMENT, padx=30, pady=16)
        foot.pack(fill="x", side="bottom")

        tk.Button(foot, text="Complete Setup - Create Desktop Shortcut",
                  font=("Arial", 10, "bold"), fg=WHITE, bg=BURGUNDY,
                  activebackground="#8B2233", activeforeground=WHITE,
                  bd=0, padx=10, pady=10, cursor="hand2",
                  wraplength=400,
                  command=self._finish).pack(fill="x")

        tk.Label(foot,
                 text="You only need to run this wizard once.\n"
                      "Use the desktop shortcut to launch the app.",
                 font=("Arial", 8), fg="#7A6650", bg=PARCHMENT,
                 justify="center").pack(pady=(8, 0))

    def _finish(self):
        # Validate
        errors = []
        if not self.gs_name.get().strip():
            errors.append("Your name is required.")
        if not self.gmail.get().strip():
            errors.append("Gmail address is required.")
        if "@" not in self.gmail.get():
            errors.append("Gmail address doesn't look valid.")
        if not self.app_password.get().strip():
            errors.append("App Password is required.")
        if not self.anthropic_key.get().strip():
            errors.append("Anthropic API key is required.")

        if errors:
            messagebox.showerror("Please fix these issues",
                                 "\n".join(f"? {e}" for e in errors))
            return

        try:
            # Write config
            write_config({
                "chapter_name":  self.chapter_name.get().strip(),
                "gs_name":       self.gs_name.get().strip(),
                "gmail":         self.gmail.get().strip(),
                "app_password":  self.app_password.get().strip(),
                "anthropic_key": self.anthropic_key.get().strip(),
            })

            # Ensure admin account can log in
            ensure_admin_can_login()

            # Create launcher.bat
            bat = create_launcher()

            # Create desktop shortcut
            create_shortcut(bat)

            messagebox.showinfo(
                "Setup complete!",
                "Chevalier Events is ready.\n\n"
                "A shortcut has been added to your Desktop.\n"
                "Double-click it anytime to launch the app."
            )
            self.destroy()

        except Exception as ex:
            messagebox.showerror("Setup failed", str(ex))


if __name__ == "__main__":
    app = SetupWizard()
    app.mainloop()
